export const ADD_PARCEL = 'ADD_PARCEL';
export const UPDATE_PARCEL = 'UPDATE_PARCEL';
export const REMOVE_PARCEL = 'REMOVE_PARCEL';
export const API_REQUEST_STARTED = 'API_REQUEST_STARTED';
export const API_REQUEST_ENDED = 'API_REQUEST_ENDED';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
